config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  #  if session[:usuario_actual]['tipo'] == 'ADM'
  mount Sidekiq::Web => '/sidekiq'
  #  end

  root to: 'login#index'
  # health_check_routes
  mount HealthMonitor::Engine, at: '/'

  post '/proxy/request_proxy', to: 'proxy#request_proxy'
  post '/proxy_royal', to: 'proxy#proxy_royal' 
  post '/proxy_inmejorable', to: 'proxy_inmejorable#proxy_caballos' 

  resources :bases_urls
  post '/bases_urls/update', to: 'bases_urls#update'
  resources :login, only: %i[index create destroy]
  post '/home/actualizar_datos', to: 'home#actualizar_datos'
  get '/home/pizarra_propuestas', to: 'home#pizarra_propuestas'
  resources :home, only: [:index]
  resources :hipodromos
  post '/jornadas/eliminar_jornada', to: 'jornadas#eliminar_jornada'
  resources :factor_cambio
  post '/factor_cambio/create', to: 'factor_cambio#create'
  get '/factor_cambio/consulta', to: 'factor_cambio#consulta'
  resources :tasas_cambio
  post '/tasas_cambio/create', to: 'tasas_cambio#create'
  get '/tasas_cambio/edit_by_group', to: 'tasas_cambio#edit_by_group'
  post '/tasas_cambio/por_agentes', to: 'tasas_cambio#por_agentes'

  resources :jornadas
  resources :juegos
  resources :ligas
  post '/equipos/buscar_liga', to: 'equipos#buscar_liga'
  resources :equipos
  resources :matchs
  post '/matchs/buscar_liga', to: 'matchs#buscar_liga'
  post '/matchs/cerrar_match', to: 'matchs#cerrar_match'

  resources :integradores
  post '/carreras/detalle', to: 'carreras#detalle'
  get '/carreras/consultar_llaves', to: 'carreras#consultar_llaves'
  resources :carreras
  get '/retirados/retirados_pendiente', to: 'retirados#retirados_pendiente'
  post '/retirados/retirar_pendientes', to: 'retirados#retirar_pendientes'
  resources :retirados
  resources :grupos
  resources :intermediarios
  resources :cobradores, path: '/agentes'

  # get '/agentes', to: 'cobradores#index'
  # get '/agentes/show', to: 'cobradores#show'

  resources :taquillas
  resources :cajero_taquilla
  resources :taquilla_grupos
  resources :premiar
  post '/usuarios/buscar_tipo', to: 'usuarios#buscar_tipo'
  resources :usuarios
  resources :cuentas_banca
  get '/solicitudes/movimiento_cajero', to: 'solicitudes#movimiento_cajero'
  post '/solicitudes/movimiento_cajero_reporte', to: 'solicitudes#movimiento_cajero_reporte'
  post '/retirados/crear_caballos', to: 'retirados#crear_caballos'
  post '/retirados/retirar', to: 'retirados#retirar'
  get '/configuracion/posttime', to: 'configuracion#posttime'
  get '/configuracion/reglas', to: 'configuracion#reglas'
  post '/configuracion/grabar_reglas', to: 'configuracion#grabar_reglas'
  post '/configuracion/buscar_carrera', to: 'configuracion#buscar_carrera'
  post '/configuracion/buscar_carrera2', to: 'configuracion#buscar_carrera2'
  post '/configuracion/cambiar_hora', to: 'configuracion#cambiar_hora'
  post '/configuracion/cerrar_carrera', to: 'configuracion#cerrar_carrera'
  post '/cuentas_banca/create', to: 'cuentas_banca#create'
  post '/taquillas/validar_correo', to: 'taquillas#validar_correo'
  # post '/taquillas_grupo/create', to:'taquillas_grupo#create'
  get '/solicitudes/recargas', to: 'solicitudes#recargas'
  get '/solicitudes/retiros', to: 'solicitudes#retiros'
  post '/solicitudes/verificar_recarga', to: 'solicitudes#verificar_recarga'
  post '/solicitudes/procesar_recarga', to: 'solicitudes#procesar_recarga'
  post '/solicitudes/procesar_retiro', to: 'solicitudes#procesar_retiro'

  post '/carreras/buscar_jornadas', to: 'carreras#buscar_jornadas'
  post '/carreras/buscar_carreras', to: 'carreras#buscar_carreras'
  post '/carreras/buscar_caballos', to: 'carreras#buscar_caballos'
  post '/carreras/crear_caballos', to: 'carreras#crear_caballos'
  post '/carreras/crear_caballos2', to: 'carreras#crear_caballos2'
  post '/carreras/crear_final_carrera', to: 'carreras#crear_final_carrera'
  post '/login/desloguear_taquilla', to: 'login#desloguear_taquilla'
  post '/taquillas/buscar_por_grupo', to: 'taquillas#buscar_por_grupo'
  post '/premiar/buscar_jornadas', to: 'premiar#buscar_jornadas'
  post '/premiar/buscar_caballos', to: 'premiar#buscar_caballos'
  post '/premiar/crear_caballos', to: 'premiar#crear_caballos'
  post '/premiar/premiar', to: 'premiar#premiar'
  get '/reportes/cuadre_general', to: 'reportes#cuadre_general'
  post '/reportes/cuadre_general_por_grupo', to: 'reportes#cuadre_general_por_grupo'
  get '/reportes/cuadre_general_caballos', to: 'reportes#cuadre_general_caballos'
  post '/reportes/cuadre_general_por_grupo_caballos', to: 'reportes#cuadre_general_por_grupo_caballos'
  get '/reportes/cuadre_general_por_grupo_caballos', to: 'reportes#cuadre_general_por_grupo_caballos'
  get '/reportes/cuadre_general_cobradores', to: 'reportes#cuadre_general_cobradores'
  post '/reportes/cuadre_general_por_grupo_cobradores', to: 'reportes#cuadre_general_por_grupo_cobradores'
  get '/reportes/cuadre_general_por_grupo_cobradores', to: 'reportes#cuadre_general_por_grupo_cobradores'

  get '/reportes/premios_ingresados_index', to: 'reportes#premios_ingresados_index'
  post '/reportes/premios_ingresados', to: 'reportes#premios_ingresados'
  get '/reportes/posttime', to: 'reportes#posttime'
  post '/reportes/posttime_consulta', to: 'reportes#posttime_consulta'
  get '/reportes/solicitudes', to: 'reportes#solicitudes'
  get '/reportes/movimientos', to: 'reportes#movimientos'
  post '/reportes/solicitudes', to: 'reportes#solicitudes_filtradas'
  post '/solicitudes/mostrar_imagen', to: 'solicitudes#mostrar_imagen'
  post '/solicitudes/verificar_retiro', to: 'solicitudes#verificar_retiro'
  post '/solicitudes/revisar_solicitudes_pendientes', to: 'solicitudes#revisar_solicitudes_pendientes'
  post '/solicitudes/get_solicitudes_pendientes', to: 'solicitudes#get_solicitudes_pendientes'
  get '/solicitudes/ajustar_saldos', to: 'solicitudes#ajustar_saldos'
  post '/solicitudes/ajustar_monto', to: 'solicitudes#ajustar_monto'

  get '/solicitudes/ajustar_saldos', to: 'solicitudes#ajustar_saldos'
  post '/retirados/buscar_carreras', to: 'retirados#buscar_carreras'
  get '/configuracion/masivo', to: 'configuracion#masivo'
  post '/configuracion/bloqueo_masivo', to: 'configuracion#bloqueo_masivo'
  post '/reportes/movimientos_taquilla', to: 'reportes#movimientos_taquilla'

  get '/reportes/cuadre_general_grupo', to: 'reportes#cuadre_general_grupo'
  post '/reportes/cuadre_general_grupo2', to: 'reportes#cuadre_general_grupo2'

  get '/deportes/premiar', to: 'deportes#premiar'
  post '/deportes/buscar_deportes', to: 'deportes#buscar_deportes'
  post '/deportes/buscar_ligas', to: 'deportes#buscar_ligas'
  post '/deportes/buscar_matchs', to: 'deportes#buscar_matchs'
  post '/deportes/buscar_juego', to: 'deportes#buscar_juego'
  post '/deportes/premiar_juego', to: 'deportes#premiar_juego'
  post '/solicitudes/verificar_tasa', to: 'solicitudes#verificar_tasa'
  get  '/reportes/historial_tasa', to: 'reportes#historial_tasa'
  post '/reportes/historial_tasas', to: 'reportes#historial_tasas'
  get  '/reportes/historial_tasa_grupo', to: 'reportes#historial_tasa_grupo'
  post '/reportes/historial_tasas_grupo', to: 'reportes#historial_tasas_grupo'

  get  '/reportes/carreras_cerradas', to: 'reportes#carreras_cerradas'
  post '/reportes/carreras_cerradas_fecha', to: 'reportes#carreras_cerradas_fecha'

  get '/reportes/premios_ingresados_deportes', to: 'reportes#premios_ingresados_deportes'
  post '/reportes/premios_ingresados_ingresados_consulta', to: 'reportes#premios_ingresados_ingresados_consulta'
  get '/reportes/pases_cajero_externo', to: 'reportes#pases_cajero_externo'
  post '/reportes/buscar_carreras_cerradas_fecha', to: 'reportes#buscar_carreras_cerradas_fecha'
  post '/reportes/consultar_pase_cajero_externo', to: 'reportes#consultar_pase_cajero_externo'
  get '/reportes/cuadre_general_externo', to: 'reportes#cuadre_general_externo'
  post '/reportes/cuadre_general_por_agentes_externo', to: 'reportes#cuadre_general_por_agentes_externo'
  get '/reportes/cuadre_general_por_agentes_externo', to: 'reportes#cuadre_general_por_agentes_externo'

  get '/reportes/cuadre_general_externo_general', to: 'reportes#cuadre_general_externo_general'
  post '/reportes/cuadre_general_por_agentes_externo_general',
       to: 'reportes#cuadre_general_por_agentes_externo_general'
  get '/reportes/cuadre_general_por_agentes_externo_general',
      to: 'reportes#cuadre_general_por_agentes_externo_general'
  get '/reportes/relacion_tickets', to: 'reportes#relacion_tickets'
  post '/reportes/relacion_tickets_detalle', to: 'reportes#relacion_tickets_detalle'
  get '/reportes/jugadas_pendientes', to: 'reportes#jugadas_pendientes'
  post '/reportes/buscar_jugadas_pendientes', to: 'reportes#buscar_jugadas_pendientes'


  get '/tablas', to: 'tablas#index'
  post '/tablas/buscar_carreras', to: 'tablas#buscar_carreras'
  post '/tablas/crear_caballos', to: 'tablas#crear_caballos'
  post '/tablas/procesar_carga', to: 'tablas#procesar_carga'
  post '/api/get_currencys', to: 'api#get_currencys'
  post '/api/update_exchange_rate', to: 'api#update_exchange_rate'
  post '/api/get_config', to: 'api#get_config'
  post '/api/set_config', to: 'api#set_config'
  post '/api/award_race', to: 'unica/api#award_race'
  post '/api/post_time', to: 'unica/api#post_time'
  post '/api/retirar_interno', to: 'unica/api#retirar_interno'
  post '/api/premiar_interno', to: 'unica/api#premiar_interno'
  post '/api/invalidate_horse', to: 'unica/api#invalidate_horse'
  post '/api/close_race', to: 'unica/api#close_race'
  post '/api/cierre_carrera_interno', to: 'unica/api#cierre_carrera_interno'
  post '/api/activate_horse', to: 'unica/api#activate_horse'
  post '/api/operations_failds', to: 'api#operations_failds'
  post '/api/set_max_min', to: 'api#set_max_min'
  get '/premiar/premiar_proxima_api', to: 'premiar#premiar_proxima_api'
  post '/ligas/filtrar', to: 'ligas#filtrar'
  post '/ligas/filtrar', to: 'hipodromos#filtrar'

app/models/factor_cambio.rb
class FactorCambio < ApplicationRecord
  belongs_to :agentes, class_name: 'Cobradore', foreign_key: "cobrador_id"

  def moneda
    mon = Moneda.find(self.moneda_id)
    [mon.abreviatura,mon.pais]
  end

end

app/controllers/factor_cambio_controller.rb
class FactorCambioController < ApplicationController
    before_action :set_factor, only: [:edit, :update, :destroy]
    skip_before_action :verify_authenticity_token
    before_action :check_user_auth, only: [:show, :index]
    before_action :seguridad_cuentas, only: [:index,:edit, :new]

  def index
     @factor = FactorCambio.where(grupo_id: session[:usuario_actual]['grupo_id'].to_i, cobrador_id: session[:usuario_actual]['cobrador_id'].to_i).order(:id)
  end

  def consulta
    @factor = FactorCambio.where(grupo_id: session[:usuario_actual]['grupo_id'].to_i, cobrador_id: session[:usuario_actual]['cobrador_id'].to_i).order(:id)
  end

  def show
    @factor = FactorCambio.where(grupo_id: session[:usuario_actual]['grupo_id'].to_i, cobrador_id: session[:usuario_actual]['cobrador_id'].to_i).order(:id)
  end

  def new
    @monedas = Moneda.all
    @factor = FactorCambio.new
    @url = 'create'
  end

  def create
    obtenet_data = request.location.data()
    @factor = FactorCambio.new(moneda_id: params[:moneda], valor_dolar: params[:tasa], grupo_id: session[:usuario_actual]['grupo_id'].to_i,cobrador_id: session[:usuario_actual]['cobrador_id'].to_i)
    if @factor.save
      HistorialTasa.create(user_id: session[:usuario_actual]['id'].to_i, moneda_id: params[:moneda], tasa_anterior: 0, tasa_nueva: params[:tasa], ip_remota: request.remote_ip, grupo_id: session[:usuario_actual]['grupo_id'].to_i, cobrador_id: session[:usuario_actual]["cobrador_id"].to_i, geo: obtenet_data.to_json)
      flash[:notice] = 'Tasa creada.'
      respond_to do |format|
        format.html { redirect_to '/factor_cambio'}
        format.json { head :no_content }
      end
    end
  end

  def edit
    @monedas = Moneda.all
    @url = factor_cambio_path(@factor)
  end

  def update
    obtenet_data = request.location.data()

    valor_anterior = @factor.valor_dolar.to_f
    if @factor.update(moneda_id: params[:moneda], valor_dolar: params[:tasa])
       agente_id = @factor.cobrador_id
       UsuariosTaquilla.where(cobrador_id: agente_id).update_all(moneda_default_dolar: params[:tasa], updated_at: DateTime.now)
       HistorialTasa.create(user_id: session[:usuario_actual]['id'].to_i, moneda_id: params[:moneda], tasa_anterior: valor_anterior.to_f, tasa_nueva: params[:tasa], ip_remota: request.remote_ip, grupo_id: session[:usuario_actual]['grupo_id'].to_i, cobrador_id: session[:usuario_actual]["cobrador_id"].to_i, geo: obtenet_data.to_json)
       flash[:notice] = 'Tasa actualizada.'
       respond_to do |format|
         format.html { redirect_to '/factor_cambio', notice: 'Tasa modificada.' }
         format.json { head :no_content }
       end
    end
  end

  def destroy
    @cuentas_banca.destroy
    respond_to do |format|
      format.html { redirect_to '/cuentas_banca' }
      format.json { head :no_content }
    end
  end



  private def set_factor
    @factor = FactorCambio.find(params[:id])
  end




  end

app/views/factor_cambio/_form.html.erb
<div class="box">


  <div class="box-body">

    <div class="box-body">
    <div class="form-group col-sm-4">
        <label for="banco">Moneda</label>
        <select size=1 class="form-control" placeholder="Moneda"  name="moneda" id="moneda" >
          <option value="0" >Selecciona Moneda</option>
        <%for moneda in @monedas%>
           <option value="<%= moneda.id%>" <%= @factor.moneda_id == moneda.id ? "selected":"" %>><%= moneda.abreviatura%> (<%= moneda.pais%>)</option>
        <%end%>
        </select>
      </div>
      <div class="form-group col-sm-4">
        <%= f.label :valor_dolar %>
        <input type="number" step="0.01" class="form-control" placeholder="Tasa" required="true" name="tasa" value="<%= @factor.valor_dolar%>">
        <span class="help-block"><i>* Este campo es requerido</i><span>
      </div>

   </div>
</div>
</div>


<script>
   function mostrar_nombre_banco(id){
     if (id == "0"){
       $('#nombre_banco').show();
     }else{
       $('#nombre_banco').hide();
     }
   }
</script>

app/views/factor_cambio/_form_edit.html.erb
<div class="box">


  <div class="box-body">

    <div class="box-body">
    <div class="form-group col-sm-4">
        <label for="banco">Banco</label>
        <select size=1 class="form-control" placeholder="banco"  name="cuentas_banca[banco_id]" id="cuentas_banca_banco_id" onchange="mostrar_nombre_banco(this.value);">
        <%for banco in @bancos%>
           <option value="<%= banco.banco_id%>" <%= @cuentas_banca.banco_id == banco.banco_id ? "selected":"" %>><%= banco.nombre%></option>
        <%end%>
        </select>
      </div>



      <div class="form-group col-sm-4">
        <%= f.label :numero_cuenta %>
        <%= f.text_field :numero_cuenta, class: "form-control", placeholder: "Numero de Cuenta", required: true %>
        <span class="help-block"><i>* Este campo es requerido</i><span>
      </div>

      <div class="form-group  col-sm-4">
        <label for="cuenta_tipo">Tipo</label>
        <select size=1 class="form-control" placeholder="Tipo"  name="cuentas_banca[tipo_cuenta]" id="cuentas_banca_tipo_cuenta" />
          <option value=1 <%= @cuentas_banca.tipo_cuenta == 1 ? "selected":"" %>>Ahorro</option>
          <option value=2 <%= @cuentas_banca.tipo_cuenta == 2 ? "selected":"" %>>Corriente</option>
          <option value=3 <%= @cuentas_banca.tipo_cuenta == 3 ? "selected":"" %>>Fal</option>
        </select>
      </div>
   </div>
   <div class="box-body">

      <div class="form-group  col-sm-4">
        <label for="moneda">Moneda</label>
        <select size=1 class="form-control" placeholder="Moneda"  name="cuentas_banca[moneda]" id="cuentas_banca_moneda" />
        <%for moneda in Moneda.where("length(abreviatura) > 0")%>
           <option value="<%= moneda.id%>" <%= @cuentas_banca.moneda == moneda.id ? "selected":"" %>><%= moneda.abreviatura + " - " + moneda.pais%></option>
        <%end%>
        </select>
      </div>


      <div class="form-group col-sm-4">
        <label for="nombre">Nombre a quien pertenece la cuenta</label>
        <%= f.text_field :nombre_cuenta, class: "form-control", placeholder: "Nombre", required: true %>
        <span class="help-block"><i>* Este campo es requerido</i><span>
      </div>

      <div class="form-group col-sm-4">
        <label for="cedula">Cedula/Rif de la cuenta</label>
        <%= f.text_field :cedula_cuenta, class: "form-control", placeholder: "cedula", required: true %>
        <span class="help-block"><i>* Este campo es requerido</i><span>
      </div>
   </div>
   <div class="box-body">
      <div class="form-group col-sm-12">
        <label for="correo">Correo de la cuenta</label>
        <%= f.text_field :email_cuenta, class: "form-control", placeholder: "Correo", required: true %>
        <span class="help-block"><i>* Este campo es requerido</i><span>
      </div>
  </div>
</div>
</div>


<script>
   function mostrar_nombre_banco(id){
     if (id == "0"){
       $('#nombre_banco').show();
     }else{
       $('#nombre_banco').hide();
     }
   }
</script>

app/views/factor_cambio/edit.html.erb
<%= form_for @factor, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Editando Tasa</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'factor_cambio/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancelar', '/factor_cambio', class: 'btn btn-danger' %>
          <%= f.submit 'Enviar', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/factor_cambio/index.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Listado de Tasas</h3>
        </div>

        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
                <table id="user_index" class="table table-bordered table-striped dataTable" role="grid">
                  <thead>
                    <tr>
                      <th>Moneda</th>
                      <th>Factor Cambio</th>
                      <th>Accion</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @factor.each do |factor| %>
                      <tr>
                        <td> <%= factor.moneda[0] + " (" + factor.moneda[1] +")" %> </td>
                        <td> <%= factor.valor_dolar %> </td>
                        <td>
                          <div class="btn-row">
                            <%= link_to raw('<i class="fa fa-cogs"></i>'), edit_factor_cambio_url(factor.id), class: 'btn btn-sm btn-warning' %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>
<%if FactorCambio.where(cobrador_id: session[:usuario_actual]['cobrador_id']).length == 0%>
  <div class="row">
    <div class="col-md-2 col-md-offset-10">
      <%= link_to 'Nueva Tasa', new_factor_cambio_path, class: 'btn btn-success pull-right' %>
    </div>
  </div>
<%end%>

app/views/factor_cambio/new.html.erb
<%= form_for @factor, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Nueva Tasa</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'factor_cambio/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancelar', '/factor_cambio', class: 'btn btn-danger' %>
          <%= f.submit 'Enviar', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/factor_cambio/show.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Listado de Tasas</h3>
        </div>

        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
                <table id="user_index" class="table table-bordered table-striped dataTable" role="grid">
                  <thead>
                    <tr>
                      <th>Moneda</th>
                      <th>Factor Cambio</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @factor.each do |factor| %>
                      <tr>
                        <td> <%= factor.moneda[0] + " (" + factor.moneda[1] +")" %> </td>
                        <td> <%= factor.valor_dolar %> </td>
                      </tr>
                    <% end %>
                  </tbody>

                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>