config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  #  if session[:usuario_actual]['tipo'] == 'ADM'
  mount Sidekiq::Web => '/sidekiq'
  #  end

  root to: 'login#index'
  # health_check_routes
  mount HealthMonitor::Engine, at: '/'

  post '/proxy/request_proxy', to: 'proxy#request_proxy'
  post '/proxy_royal', to: 'proxy#proxy_royal' 
  post '/proxy_inmejorable', to: 'proxy_inmejorable#proxy_caballos' 

  resources :bases_urls
  post '/bases_urls/update', to: 'bases_urls#update'
  resources :login, only: %i[index create destroy]
  post '/home/actualizar_datos', to: 'home#actualizar_datos'
  get '/home/pizarra_propuestas', to: 'home#pizarra_propuestas'
  resources :home, only: [:index]
  resources :hipodromos
  post '/jornadas/eliminar_jornada', to: 'jornadas#eliminar_jornada'
  resources :factor_cambio
  post '/factor_cambio/create', to: 'factor_cambio#create'
  get '/factor_cambio/consulta', to: 'factor_cambio#consulta'
  resources :tasas_cambio
  post '/tasas_cambio/create', to: 'tasas_cambio#create'
  get '/tasas_cambio/edit_by_group', to: 'tasas_cambio#edit_by_group'
  post '/tasas_cambio/por_agentes', to: 'tasas_cambio#por_agentes'

  resources :jornadas
  resources :juegos
  resources :ligas
  post '/equipos/buscar_liga', to: 'equipos#buscar_liga'
  resources :equipos
  resources :matchs
  post '/matchs/buscar_liga', to: 'matchs#buscar_liga'
  post '/matchs/cerrar_match', to: 'matchs#cerrar_match'

  resources :integradores
  post '/carreras/detalle', to: 'carreras#detalle'
  get '/carreras/consultar_llaves', to: 'carreras#consultar_llaves'
  resources :carreras
  get '/retirados/retirados_pendiente', to: 'retirados#retirados_pendiente'
  post '/retirados/retirar_pendientes', to: 'retirados#retirar_pendientes'
  resources :retirados
  resources :grupos
  resources :intermediarios
  resources :cobradores, path: '/agentes'

  # get '/agentes', to: 'cobradores#index'
  # get '/agentes/show', to: 'cobradores#show'

  resources :taquillas
  resources :cajero_taquilla
  resources :taquilla_grupos
  resources :premiar
  post '/usuarios/buscar_tipo', to: 'usuarios#buscar_tipo'
  resources :usuarios
  resources :cuentas_banca
  get '/solicitudes/movimiento_cajero', to: 'solicitudes#movimiento_cajero'
  post '/solicitudes/movimiento_cajero_reporte', to: 'solicitudes#movimiento_cajero_reporte'
  post '/retirados/crear_caballos', to: 'retirados#crear_caballos'
  post '/retirados/retirar', to: 'retirados#retirar'
  get '/configuracion/posttime', to: 'configuracion#posttime'
  get '/configuracion/reglas', to: 'configuracion#reglas'
  post '/configuracion/grabar_reglas', to: 'configuracion#grabar_reglas'
  post '/configuracion/buscar_carrera', to: 'configuracion#buscar_carrera'
  post '/configuracion/buscar_carrera2', to: 'configuracion#buscar_carrera2'
  post '/configuracion/cambiar_hora', to: 'configuracion#cambiar_hora'
  post '/configuracion/cerrar_carrera', to: 'configuracion#cerrar_carrera'
  post '/cuentas_banca/create', to: 'cuentas_banca#create'
  post '/taquillas/validar_correo', to: 'taquillas#validar_correo'
  # post '/taquillas_grupo/create', to:'taquillas_grupo#create'
  get '/solicitudes/recargas', to: 'solicitudes#recargas'
  get '/solicitudes/retiros', to: 'solicitudes#retiros'
  post '/solicitudes/verificar_recarga', to: 'solicitudes#verificar_recarga'
  post '/solicitudes/procesar_recarga', to: 'solicitudes#procesar_recarga'
  post '/solicitudes/procesar_retiro', to: 'solicitudes#procesar_retiro'

  post '/carreras/buscar_jornadas', to: 'carreras#buscar_jornadas'
  post '/carreras/buscar_carreras', to: 'carreras#buscar_carreras'
  post '/carreras/buscar_caballos', to: 'carreras#buscar_caballos'
  post '/carreras/crear_caballos', to: 'carreras#crear_caballos'
  post '/carreras/crear_caballos2', to: 'carreras#crear_caballos2'
  post '/carreras/crear_final_carrera', to: 'carreras#crear_final_carrera'
  post '/login/desloguear_taquilla', to: 'login#desloguear_taquilla'
  post '/taquillas/buscar_por_grupo', to: 'taquillas#buscar_por_grupo'
  post '/premiar/buscar_jornadas', to: 'premiar#buscar_jornadas'
  post '/premiar/buscar_caballos', to: 'premiar#buscar_caballos'
  post '/premiar/crear_caballos', to: 'premiar#crear_caballos'
  post '/premiar/premiar', to: 'premiar#premiar'
  get '/reportes/cuadre_general', to: 'reportes#cuadre_general'
  post '/reportes/cuadre_general_por_grupo', to: 'reportes#cuadre_general_por_grupo'
  get '/reportes/cuadre_general_caballos', to: 'reportes#cuadre_general_caballos'
  post '/reportes/cuadre_general_por_grupo_caballos', to: 'reportes#cuadre_general_por_grupo_caballos'
  get '/reportes/cuadre_general_por_grupo_caballos', to: 'reportes#cuadre_general_por_grupo_caballos'
  get '/reportes/cuadre_general_cobradores', to: 'reportes#cuadre_general_cobradores'
  post '/reportes/cuadre_general_por_grupo_cobradores', to: 'reportes#cuadre_general_por_grupo_cobradores'
  get '/reportes/cuadre_general_por_grupo_cobradores', to: 'reportes#cuadre_general_por_grupo_cobradores'

  get '/reportes/premios_ingresados_index', to: 'reportes#premios_ingresados_index'
  post '/reportes/premios_ingresados', to: 'reportes#premios_ingresados'
  get '/reportes/posttime', to: 'reportes#posttime'
  post '/reportes/posttime_consulta', to: 'reportes#posttime_consulta'
  get '/reportes/solicitudes', to: 'reportes#solicitudes'
  get '/reportes/movimientos', to: 'reportes#movimientos'
  post '/reportes/solicitudes', to: 'reportes#solicitudes_filtradas'
  post '/solicitudes/mostrar_imagen', to: 'solicitudes#mostrar_imagen'
  post '/solicitudes/verificar_retiro', to: 'solicitudes#verificar_retiro'
  post '/solicitudes/revisar_solicitudes_pendientes', to: 'solicitudes#revisar_solicitudes_pendientes'
  post '/solicitudes/get_solicitudes_pendientes', to: 'solicitudes#get_solicitudes_pendientes'
  get '/solicitudes/ajustar_saldos', to: 'solicitudes#ajustar_saldos'
  post '/solicitudes/ajustar_monto', to: 'solicitudes#ajustar_monto'

  get '/solicitudes/ajustar_saldos', to: 'solicitudes#ajustar_saldos'
  post '/retirados/buscar_carreras', to: 'retirados#buscar_carreras'
  get '/configuracion/masivo', to: 'configuracion#masivo'
  post '/configuracion/bloqueo_masivo', to: 'configuracion#bloqueo_masivo'
  post '/reportes/movimientos_taquilla', to: 'reportes#movimientos_taquilla'

  get '/reportes/cuadre_general_grupo', to: 'reportes#cuadre_general_grupo'
  post '/reportes/cuadre_general_grupo2', to: 'reportes#cuadre_general_grupo2'

  get '/deportes/premiar', to: 'deportes#premiar'
  post '/deportes/buscar_deportes', to: 'deportes#buscar_deportes'
  post '/deportes/buscar_ligas', to: 'deportes#buscar_ligas'
  post '/deportes/buscar_matchs', to: 'deportes#buscar_matchs'
  post '/deportes/buscar_juego', to: 'deportes#buscar_juego'
  post '/deportes/premiar_juego', to: 'deportes#premiar_juego'
  post '/solicitudes/verificar_tasa', to: 'solicitudes#verificar_tasa'
  get  '/reportes/historial_tasa', to: 'reportes#historial_tasa'
  post '/reportes/historial_tasas', to: 'reportes#historial_tasas'
  get  '/reportes/historial_tasa_grupo', to: 'reportes#historial_tasa_grupo'
  post '/reportes/historial_tasas_grupo', to: 'reportes#historial_tasas_grupo'

  get  '/reportes/carreras_cerradas', to: 'reportes#carreras_cerradas'
  post '/reportes/carreras_cerradas_fecha', to: 'reportes#carreras_cerradas_fecha'

  get '/reportes/premios_ingresados_deportes', to: 'reportes#premios_ingresados_deportes'
  post '/reportes/premios_ingresados_ingresados_consulta', to: 'reportes#premios_ingresados_ingresados_consulta'
  get '/reportes/pases_cajero_externo', to: 'reportes#pases_cajero_externo'
  post '/reportes/buscar_carreras_cerradas_fecha', to: 'reportes#buscar_carreras_cerradas_fecha'
  post '/reportes/consultar_pase_cajero_externo', to: 'reportes#consultar_pase_cajero_externo'
  get '/reportes/cuadre_general_externo', to: 'reportes#cuadre_general_externo'
  post '/reportes/cuadre_general_por_agentes_externo', to: 'reportes#cuadre_general_por_agentes_externo'
  get '/reportes/cuadre_general_por_agentes_externo', to: 'reportes#cuadre_general_por_agentes_externo'

  get '/reportes/cuadre_general_externo_general', to: 'reportes#cuadre_general_externo_general'
  post '/reportes/cuadre_general_por_agentes_externo_general',
       to: 'reportes#cuadre_general_por_agentes_externo_general'
  get '/reportes/cuadre_general_por_agentes_externo_general',
      to: 'reportes#cuadre_general_por_agentes_externo_general'
  get '/reportes/relacion_tickets', to: 'reportes#relacion_tickets'
  post '/reportes/relacion_tickets_detalle', to: 'reportes#relacion_tickets_detalle'
  get '/reportes/jugadas_pendientes', to: 'reportes#jugadas_pendientes'
  post '/reportes/buscar_jugadas_pendientes', to: 'reportes#buscar_jugadas_pendientes'


  get '/tablas', to: 'tablas#index'
  post '/tablas/buscar_carreras', to: 'tablas#buscar_carreras'
  post '/tablas/crear_caballos', to: 'tablas#crear_caballos'
  post '/tablas/procesar_carga', to: 'tablas#procesar_carga'
  post '/api/get_currencys', to: 'api#get_currencys'
  post '/api/update_exchange_rate', to: 'api#update_exchange_rate'
  post '/api/get_config', to: 'api#get_config'
  post '/api/set_config', to: 'api#set_config'
  post '/api/award_race', to: 'unica/api#award_race'
  post '/api/post_time', to: 'unica/api#post_time'
  post '/api/retirar_interno', to: 'unica/api#retirar_interno'
  post '/api/premiar_interno', to: 'unica/api#premiar_interno'
  post '/api/invalidate_horse', to: 'unica/api#invalidate_horse'
  post '/api/close_race', to: 'unica/api#close_race'
  post '/api/cierre_carrera_interno', to: 'unica/api#cierre_carrera_interno'
  post '/api/activate_horse', to: 'unica/api#activate_horse'
  post '/api/operations_failds', to: 'api#operations_failds'
  post '/api/set_max_min', to: 'api#set_max_min'
  get '/premiar/premiar_proxima_api', to: 'premiar#premiar_proxima_api'
  post '/ligas/filtrar', to: 'ligas#filtrar'
  post '/ligas/filtrar', to: 'hipodromos#filtrar'

app/models/match.rb
class Match < ApplicationRecord
  include ApplicationHelper
  belongs_to :juego, primary_key: "juego_id"
  belongs_to :liga, primary_key: "liga_id"
  has_many :propuestas_deportes
  after_update :actualizo
  after_create :nuevo_match

  def detalle_match
   deporte = Juego.find_by(juego_id: self.juego_id)
   liga = Liga.find_by(liga_id: self.liga_id)
   "#{deporte.nombre} Liga #{liga.nombre}/#{self.nombre}"
  end

  def nuevo_match
    ActionCable.server.broadcast "publicas_deporte_channel", { data: { "tipo" => "UPDATE_LIGA", "data_menu" => menu_deportes_helper(self.juego_id), "deporte_id" => self.juego_id, "liga_id" => self.liga_id }}
  end

  def actualizo
    datos = JSON.parse(self.data)
    logros_sistema = { "money_line" => [], "run_line" => [], "alta_baja" => [] }
    money_line = []
    run_line = []
    alta_baja = []
    if self.juego_id == 12
      if datos["money_line"].length > 0
        dat_money = datos["money_line"]["c"]
        money_line = [{ "o" => dat_money[1]["o"], "uk" => dat_money[1]["uk"], "us" => dat_money[1]["us"] }, { "o" => dat_money[2]["o"], "uk" => dat_money[2]["uk"], "us" => dat_money[2]["us"] }, { "o" => dat_money[0]["o"], "uk" => dat_money[0]["uk"], "us" => dat_money[0]["us"] }]
      else
        money_line = [false, false, false]
      end
      run_line = [false, false]
      if datos["alta_baja"].length > 0
        dat_altabaja = datos["alta_baja"]["c"]
        alta_baja = [{ "o" => dat_altabaja[0]["o"], "uk" => dat_altabaja[0]["uk"], "us" => dat_altabaja[0]["us"], "l" => dat_altabaja[0]["l"] }, { "o" => dat_altabaja[1]["o"], "uk" => dat_altabaja[1]["uk"], "us" => dat_altabaja[1]["us"], "l" => dat_altabaja[0]["l"] }]
      else
        alta_baja = [false, false]
      end
      logros_sistema = { "money_line" => money_line, "run_line" => [false, false], "alta_baja" => alta_baja }
    else
      if datos["money_line"].length > 0
        dat_money = datos["money_line"]["c"]
        money_line = [{ "o" => dat_money[0]["o"], "uk" => dat_money[0]["uk"], "us" => dat_money[0]["us"] }, { "o" => dat_money[1]["o"], "uk" => dat_money[1]["uk"], "us" => dat_money[1]["us"] }]
      else
        money_line = [false, false]
      end
      if datos["run_line"].length > 0
        dat_runline = datos["run_line"]["c"]
        run_line = [{ "o" => dat_runline[0]["o"], "uk" => dat_runline[0]["uk"], "us" => dat_runline[0]["us"], "l" => dat_runline[0]["l"] }, { "o" => dat_runline[1]["o"], "uk" => dat_runline[1]["uk"], "us" => dat_runline[1]["us"], "l" => dat_runline[0]["l"] }]
      else
        run_line = [false, false]
      end
      if datos["alta_baja"].length > 0
        dat_altabaja = datos["alta_baja"]["c"]
        alta_baja = [{ "o" => dat_altabaja[0]["o"], "uk" => dat_altabaja[0]["uk"], "us" => dat_altabaja[0]["us"], "l" => dat_altabaja[0]["l"] }, { "o" => dat_altabaja[1]["o"], "uk" => dat_altabaja[1]["uk"], "us" => dat_altabaja[1]["us"], "l" => dat_altabaja[0]["l"] }]
      else
        alta_baja = [false, false]
      end
      logros_sistema = { "money_line" => money_line, "run_line" => run_line, "alta_baja" => alta_baja }
    end
    if self.activo
      ActionCable.server.broadcast "publicas_deporte_channel", { data: { "tipo" => "UPDATE_MATCH_API", "match_id" => self.id, "logros" => logros_sistema }}
    end
    # Rails.logger.error "*********************** se actualizo un logro ******************"
  end

  def nombre_deporte
    Juego.find_by(juego_id: self.juego_id).nombre
  end

  def nombre_liga
    liga = Liga.find_by(liga_id: self.liga_id)
    liga.nombre if liga.present?
  end
end

app/views/matchs/_ligas.erb
<label for="hipodromo_tipo">Liga</label>
<select size=1 class="form-control" placeholder="Tipo"  name="liga_id" id="liga_id" >
<%for liga in @ligas%>
  <option value="<%= liga.liga_id %>"  ><%= liga.nombre %></option>
<%end%>
</select>

app/views/matchs/_ligas_edit.erb
<label for="hipodromo_tipo">Liga</label>
<select size=1 class="form-control" placeholder="Tipo"  name="liga_id" id="liga_id" >
<%for liga in @ligas%>
  <option value="<%= liga.liga_id %>"  <%= @match.liga_id == liga.liga_id ? "selected":"" %>><%= liga.nombre %></option>
<%end%>
</select>

app/views/matchs/edit.html.erb
<%= form_for @match, url: @url, role: :form, html: { multipart: true } do |f| %>
<div class="row">
  <div class="col-xs-12">
    <div class="box">

      <div class="box-header">
        <h3 class="box-title">Editando Match</h3>
      </div>

      <div class="box-body">
        <%= render partial: 'matchs/form_edit', locals: { f: f } %>
      </div>

      <div class="box-footer">
        <%= link_to 'Cancelar', matchs_path, class: 'btn btn-danger' %>
        <%= f.submit 'Enviar', class: "btn btn-success"%>
      </div>

    </div>
  </div>
</div>

<% end %>

app/views/matchs/index.html.erb
<script>
function myFunction() {
  
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("mysearch");
  filter = input.value.toUpperCase();
  table = document.getElementById("matches");
  tr = table.getElementsByTagName("tr");

  
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}


function cerrar_match(id){
    swal({
    title: "Advertencia",
    text: "Esta seguro de cerrar este match?",
    icon: "warning",
      dangerMode: false,
    buttons: {
    confirm: "Aceptar",
      cancel: "Cancelar",
      },
  })
  .then((willDelete) => {
    if (willDelete) {
            axios({
                method: 'POST',
                  url: '/matchs/cerrar_match',
                data: {
                  "id": id
                },
              })
              .then(function(response) {
                swal("Completo", "Match Cerrado con exito.", "success").then((aceptar) => {
                  location.reload(true);
                });
              }
            )
            .catch(function (error) {
                swal("Lo siento", "Ocurrio un error. Verifique todos los datos", "error");
            });
       }  
  })

}

</script>

<style>
#mysearch {
  background-image: url('/assets/searchicon.png'); /* Add a search icon to input */
  background-position: 10px 12px; /* Position the search icon */
  background-repeat: no-repeat; /* Do not repeat the icon image */
  width: 100%; /* Full-width */
  font-size: 16px; /* Increase font-size */
  padding: 12px 20px 12px 40px; /* Add some padding */
  border: 1px solid #ddd; /* Add a grey border */
  margin-bottom: 12px; /* Add some space below the input */
}
</style>

<div class="row">
  <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Listado de Match</h3>
        </div>

        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">

                <input type="text" id="mysearch" onkeyup="myFunction()" placeholder="Ingrese deporte">
                <div class="row">
                  <div class="col-md-2 col-md-offset-10">
                    <%= link_to 'Nuevo Match', new_match_path, class: 'btn btn-success pull-right' %>
                  </div>
                </div>
                <table id="matches" class="table table-bordered table-striped dataTable" role="grid">
                  <thead>
                    <tr>
                      <th>Match ID</th>
                      <th>Tipo Juego</th>
                      <th>Liga</th>
                      <th>Match</th>
                      <th>Hora Juego</th>
                      <th style="width: 5%;text-align: center;">Editar</th>
                      <th style="width: 5%;text-align: center;">Cerrar</th>
                      <th style="width: 5%;text-align: center;">Eliminar</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @matchs.each do |match| %>
                    <%color = (match.local < Time.now or match.activo == false) ? "red":"white"%>
                    <%letras = match.local < Time.now ? "white":"black"%>
                      <tr>
                        <td style="background-color: <%= color%>;color: <%= letras%>"> <%= match.match_id %> </td>
                        <td  style="background-color: <%= color%>;color: <%= letras%>"> <%= match.nombre_deporte %> </td>
                        <td  style="background-color: <%= color%>;color: <%= letras%>"> <%= match.nombre_liga %> </td>
                        <td  style="background-color: <%= color%>;color: <%= letras%>"> <%= match.nombre %> </td>
                        <td  style="background-color: <%= color%>;color: <%= letras%>"> <%= match.local.strftime("%I:%M %p") %> </td>
                        <td align="center">
                            <%= link_to raw('<i class="fa fa-cogs"></i>'), edit_match_url(match), class: 'btn btn-sm btn-success' %>
                        </td>
                        <td align="center" >
                            <%if match.activo == false %>
                              <a class='btn btn-sm btn-warning'><i class="fa fa-window-close"></i> </a>
                            <%else%>
                               <a onclick="cerrar_match(<%=match.id%>);" class='btn btn-sm btn-warning'><i class="fa fa-window-close"></i> </a>
                            <%end%>
                       </td>
                        <td align="center">
                            <%= link_to raw('<i class="fa fa-trash"></i>'), match_url(match), class: 'btn btn-sm btn-danger', method: :delete,
                                            data: { confirm: 'Esta seguro de eliminar este match?' } %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to 'Nuevo Match', new_match_path, class: 'btn btn-success pull-right' %>
  </div>
</div>

app/views/matchs/new.html.erb
<%= form_for @match, url: @url, role: :form, html: { multipart: true } do |f| %>
<div class="row">
  <div class="col-xs-12">
    <div class="box">

      <div class="box-header">
        <h3 class="box-title">Nuevo Match</h3>
      </div>

      <div class="box-body">
        <%= render partial: 'matchs/form', locals: { f: f } %>
      </div>

      <div class="box-footer">
        <%= link_to 'Cancelar', matchs_path, class: 'btn btn-danger' %>
        <input type="submit" name="commit" value="Enviar" class="btn btn-success" data-disable-with="Enviar"  id="boton_enviar_match">
      </div>

    </div>
  </div>
</div>

<% end %>