config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  #  if session[:usuario_actual]['tipo'] == 'ADM'
  mount Sidekiq::Web => '/sidekiq'
  #  end

  root to: 'login#index'
  # health_check_routes
  mount HealthMonitor::Engine, at: '/'

  post '/proxy/request_proxy', to: 'proxy#request_proxy'
  post '/proxy_royal', to: 'proxy#proxy_royal' 
  post '/proxy_inmejorable', to: 'proxy_inmejorable#proxy_caballos' 

  resources :bases_urls
  post '/bases_urls/update', to: 'bases_urls#update'
  resources :login, only: %i[index create destroy]
  post '/home/actualizar_datos', to: 'home#actualizar_datos'
  get '/home/pizarra_propuestas', to: 'home#pizarra_propuestas'
  resources :home, only: [:index]
  resources :hipodromos
  post '/jornadas/eliminar_jornada', to: 'jornadas#eliminar_jornada'
  resources :factor_cambio
  post '/factor_cambio/create', to: 'factor_cambio#create'
  get '/factor_cambio/consulta', to: 'factor_cambio#consulta'
  resources :tasas_cambio
  post '/tasas_cambio/create', to: 'tasas_cambio#create'
  get '/tasas_cambio/edit_by_group', to: 'tasas_cambio#edit_by_group'
  post '/tasas_cambio/por_agentes', to: 'tasas_cambio#por_agentes'

  resources :jornadas
  resources :juegos
  resources :ligas
  post '/equipos/buscar_liga', to: 'equipos#buscar_liga'
  resources :equipos
  resources :matchs
  post '/matchs/buscar_liga', to: 'matchs#buscar_liga'
  post '/matchs/cerrar_match', to: 'matchs#cerrar_match'

  resources :integradores
  post '/carreras/detalle', to: 'carreras#detalle'
  get '/carreras/consultar_llaves', to: 'carreras#consultar_llaves'
  resources :carreras
  get '/retirados/retirados_pendiente', to: 'retirados#retirados_pendiente'
  post '/retirados/retirar_pendientes', to: 'retirados#retirar_pendientes'
  resources :retirados
  resources :grupos
  resources :intermediarios
  resources :cobradores, path: '/agentes'

  # get '/agentes', to: 'cobradores#index'
  # get '/agentes/show', to: 'cobradores#show'

  resources :taquillas
  resources :cajero_taquilla
  resources :taquilla_grupos
  resources :premiar
  post '/usuarios/buscar_tipo', to: 'usuarios#buscar_tipo'
  resources :usuarios
  resources :cuentas_banca
  get '/solicitudes/movimiento_cajero', to: 'solicitudes#movimiento_cajero'
  post '/solicitudes/movimiento_cajero_reporte', to: 'solicitudes#movimiento_cajero_reporte'
  post '/retirados/crear_caballos', to: 'retirados#crear_caballos'
  post '/retirados/retirar', to: 'retirados#retirar'
  get '/configuracion/posttime', to: 'configuracion#posttime'
  get '/configuracion/reglas', to: 'configuracion#reglas'
  post '/configuracion/grabar_reglas', to: 'configuracion#grabar_reglas'
  post '/configuracion/buscar_carrera', to: 'configuracion#buscar_carrera'
  post '/configuracion/buscar_carrera2', to: 'configuracion#buscar_carrera2'
  post '/configuracion/cambiar_hora', to: 'configuracion#cambiar_hora'
  post '/configuracion/cerrar_carrera', to: 'configuracion#cerrar_carrera'
  post '/cuentas_banca/create', to: 'cuentas_banca#create'
  post '/taquillas/validar_correo', to: 'taquillas#validar_correo'
  # post '/taquillas_grupo/create', to:'taquillas_grupo#create'
  get '/solicitudes/recargas', to: 'solicitudes#recargas'
  get '/solicitudes/retiros', to: 'solicitudes#retiros'
  post '/solicitudes/verificar_recarga', to: 'solicitudes#verificar_recarga'
  post '/solicitudes/procesar_recarga', to: 'solicitudes#procesar_recarga'
  post '/solicitudes/procesar_retiro', to: 'solicitudes#procesar_retiro'

  post '/carreras/buscar_jornadas', to: 'carreras#buscar_jornadas'
  post '/carreras/buscar_carreras', to: 'carreras#buscar_carreras'
  post '/carreras/buscar_caballos', to: 'carreras#buscar_caballos'
  post '/carreras/crear_caballos', to: 'carreras#crear_caballos'
  post '/carreras/crear_caballos2', to: 'carreras#crear_caballos2'
  post '/carreras/crear_final_carrera', to: 'carreras#crear_final_carrera'
  post '/login/desloguear_taquilla', to: 'login#desloguear_taquilla'
  post '/taquillas/buscar_por_grupo', to: 'taquillas#buscar_por_grupo'
  post '/premiar/buscar_jornadas', to: 'premiar#buscar_jornadas'
  post '/premiar/buscar_caballos', to: 'premiar#buscar_caballos'
  post '/premiar/crear_caballos', to: 'premiar#crear_caballos'
  post '/premiar/premiar', to: 'premiar#premiar'
  get '/reportes/cuadre_general', to: 'reportes#cuadre_general'
  post '/reportes/cuadre_general_por_grupo', to: 'reportes#cuadre_general_por_grupo'
  get '/reportes/cuadre_general_caballos', to: 'reportes#cuadre_general_caballos'
  post '/reportes/cuadre_general_por_grupo_caballos', to: 'reportes#cuadre_general_por_grupo_caballos'
  get '/reportes/cuadre_general_por_grupo_caballos', to: 'reportes#cuadre_general_por_grupo_caballos'
  get '/reportes/cuadre_general_cobradores', to: 'reportes#cuadre_general_cobradores'
  post '/reportes/cuadre_general_por_grupo_cobradores', to: 'reportes#cuadre_general_por_grupo_cobradores'
  get '/reportes/cuadre_general_por_grupo_cobradores', to: 'reportes#cuadre_general_por_grupo_cobradores'

  get '/reportes/premios_ingresados_index', to: 'reportes#premios_ingresados_index'
  post '/reportes/premios_ingresados', to: 'reportes#premios_ingresados'
  get '/reportes/posttime', to: 'reportes#posttime'
  post '/reportes/posttime_consulta', to: 'reportes#posttime_consulta'
  get '/reportes/solicitudes', to: 'reportes#solicitudes'
  get '/reportes/movimientos', to: 'reportes#movimientos'
  post '/reportes/solicitudes', to: 'reportes#solicitudes_filtradas'
  post '/solicitudes/mostrar_imagen', to: 'solicitudes#mostrar_imagen'
  post '/solicitudes/verificar_retiro', to: 'solicitudes#verificar_retiro'
  post '/solicitudes/revisar_solicitudes_pendientes', to: 'solicitudes#revisar_solicitudes_pendientes'
  post '/solicitudes/get_solicitudes_pendientes', to: 'solicitudes#get_solicitudes_pendientes'
  get '/solicitudes/ajustar_saldos', to: 'solicitudes#ajustar_saldos'
  post '/solicitudes/ajustar_monto', to: 'solicitudes#ajustar_monto'

  get '/solicitudes/ajustar_saldos', to: 'solicitudes#ajustar_saldos'
  post '/retirados/buscar_carreras', to: 'retirados#buscar_carreras'
  get '/configuracion/masivo', to: 'configuracion#masivo'
  post '/configuracion/bloqueo_masivo', to: 'configuracion#bloqueo_masivo'
  post '/reportes/movimientos_taquilla', to: 'reportes#movimientos_taquilla'

  get '/reportes/cuadre_general_grupo', to: 'reportes#cuadre_general_grupo'
  post '/reportes/cuadre_general_grupo2', to: 'reportes#cuadre_general_grupo2'

  get '/deportes/premiar', to: 'deportes#premiar'
  post '/deportes/buscar_deportes', to: 'deportes#buscar_deportes'
  post '/deportes/buscar_ligas', to: 'deportes#buscar_ligas'
  post '/deportes/buscar_matchs', to: 'deportes#buscar_matchs'
  post '/deportes/buscar_juego', to: 'deportes#buscar_juego'
  post '/deportes/premiar_juego', to: 'deportes#premiar_juego'
  post '/solicitudes/verificar_tasa', to: 'solicitudes#verificar_tasa'
  get  '/reportes/historial_tasa', to: 'reportes#historial_tasa'
  post '/reportes/historial_tasas', to: 'reportes#historial_tasas'
  get  '/reportes/historial_tasa_grupo', to: 'reportes#historial_tasa_grupo'
  post '/reportes/historial_tasas_grupo', to: 'reportes#historial_tasas_grupo'

  get  '/reportes/carreras_cerradas', to: 'reportes#carreras_cerradas'
  post '/reportes/carreras_cerradas_fecha', to: 'reportes#carreras_cerradas_fecha'

  get '/reportes/premios_ingresados_deportes', to: 'reportes#premios_ingresados_deportes'
  post '/reportes/premios_ingresados_ingresados_consulta', to: 'reportes#premios_ingresados_ingresados_consulta'
  get '/reportes/pases_cajero_externo', to: 'reportes#pases_cajero_externo'
  post '/reportes/buscar_carreras_cerradas_fecha', to: 'reportes#buscar_carreras_cerradas_fecha'
  post '/reportes/consultar_pase_cajero_externo', to: 'reportes#consultar_pase_cajero_externo'
  get '/reportes/cuadre_general_externo', to: 'reportes#cuadre_general_externo'
  post '/reportes/cuadre_general_por_agentes_externo', to: 'reportes#cuadre_general_por_agentes_externo'
  get '/reportes/cuadre_general_por_agentes_externo', to: 'reportes#cuadre_general_por_agentes_externo'

  get '/reportes/cuadre_general_externo_general', to: 'reportes#cuadre_general_externo_general'
  post '/reportes/cuadre_general_por_agentes_externo_general',
       to: 'reportes#cuadre_general_por_agentes_externo_general'
  get '/reportes/cuadre_general_por_agentes_externo_general',
      to: 'reportes#cuadre_general_por_agentes_externo_general'
  get '/reportes/relacion_tickets', to: 'reportes#relacion_tickets'
  post '/reportes/relacion_tickets_detalle', to: 'reportes#relacion_tickets_detalle'
  get '/reportes/jugadas_pendientes', to: 'reportes#jugadas_pendientes'
  post '/reportes/buscar_jugadas_pendientes', to: 'reportes#buscar_jugadas_pendientes'


  get '/tablas', to: 'tablas#index'
  post '/tablas/buscar_carreras', to: 'tablas#buscar_carreras'
  post '/tablas/crear_caballos', to: 'tablas#crear_caballos'
  post '/tablas/procesar_carga', to: 'tablas#procesar_carga'
  post '/api/get_currencys', to: 'api#get_currencys'
  post '/api/update_exchange_rate', to: 'api#update_exchange_rate'
  post '/api/get_config', to: 'api#get_config'
  post '/api/set_config', to: 'api#set_config'
  post '/api/award_race', to: 'unica/api#award_race'
  post '/api/post_time', to: 'unica/api#post_time'
  post '/api/retirar_interno', to: 'unica/api#retirar_interno'
  post '/api/premiar_interno', to: 'unica/api#premiar_interno'
  post '/api/invalidate_horse', to: 'unica/api#invalidate_horse'
  post '/api/close_race', to: 'unica/api#close_race'
  post '/api/cierre_carrera_interno', to: 'unica/api#cierre_carrera_interno'
  post '/api/activate_horse', to: 'unica/api#activate_horse'
  post '/api/operations_failds', to: 'api#operations_failds'
  post '/api/set_max_min', to: 'api#set_max_min'
  get '/premiar/premiar_proxima_api', to: 'premiar#premiar_proxima_api'
  post '/ligas/filtrar', to: 'ligas#filtrar'
  post '/ligas/filtrar', to: 'hipodromos#filtrar'

app/models/jornada.rb
class Jornada < ApplicationRecord
  belongs_to :hipodromo
  has_many :carrera, dependent: :destroy
  attr_accessor :fecha_bonita

  def fecha_bonita
     return self.fecha.strftime("%d/%m/%Y")
  end
end

app/controllers/jornadas_controller.rb
  class JornadasController < ApplicationController
    skip_before_action :verify_authenticity_token
    respond_to :json, :html
    before_action :set_jornada, only: [:show, :edit, :update]
    before_action :check_user_auth, only: [:show, :index]
    before_action :seguridad_cuentas, only: [:index,:edit, :new]

    def index
      @jornadas = Jornada.where(fecha: Time.now.beginning_of_day..(Time.now + 5.days)).order(:fecha)
    end

    def show
    end

    def new
      unless session['existe'].present?
        flash.clear
      end
      @jornada = Jornada.new
      @hipodromos = Hipodromo.all.order(:nombre)
      @url = jornadas_path

    end

    def create
      buscar  = Jornada.where(hipodromo_id: params[:jornada]['hipodromo_id'].to_i , fecha: params[:jornada]['fecha'].to_time.all_day)
      if buscar.present?
          @hipodromos = Hipodromo.all.order(:nombre)
          flash[:notice] = 'Ya existe una Jornada para la fecha.'
          session['existe'] = true
          respond_to do |format|
            format.html { redirect_to '/jornadas/new' }
            format.json { head :no_content }
          end
      else
          session['existe'] = false
          @jornada = Jornada.new(jornada_params)
          if @jornada.save
            eval(params.require(:jornada)[:cantidad_carreras]).to_i.times {|tim|
               @jornada.carrera.create(hora_carrera: '', numero_carrera: tim + 1, cantidad_caballos: 0, activo: true )
            }
            @hipodromos = Hipodromo.all.order(:nombre)
            flash[:notice] = 'Jornada creada.'
            respond_to do |format|
              format.html { redirect_to '/jornadas' }
              format.json { head :no_content }
            end
          end
      end
    end

    def edit
      @hipodromos = Hipodromo.all.order(:nombre)
      @hip_act = @jornada.hipodromo_id
      @url = jornada_path(@jornada)
    end

    def update
         carreras_antiores = @jornada.cantidad_carreras.to_i
      if @jornada.update(jornada_params)
        if params[:jornada][:cantidad_carreras].to_i > carreras_antiores
          eval(params.require(:jornada)[:cantidad_carreras]).to_i.times {|tim|
            num_carr = tim + 1
            if num_carr > carreras_antiores
              @jornada.carrera.create(hora_carrera: '', numero_carrera: num_carr, cantidad_caballos: 0, activo: true )
            end
          }
        elsif params[:jornada][:cantidad_carreras].to_i < carreras_antiores
          @jornada.carrera.where(" CAST (numero_carrera AS INTEGER) > #{params[:jornada][:cantidad_carreras].to_i}").destroy_all
        end

        flash[:notice] = 'Jornada actualizado.'
        respond_to do |format|
          format.html { redirect_to '/jornadas' }
          format.json { head :no_content }
        end
      end
    end

    def eliminar_jornada
       jor = Jornada.find_by(id: params[:id])
       if jor.present?
         jor.destroy
       end
       render json: {"status" => "OK"}
      # respond_to do |format|
      #   format.html { redirect_to '/jornadas' }
      #   format.json { head :no_content }
      # end
    end


    private def set_jornada
      @jornada = Jornada.find(params[:id])
    end


    private def jornada_params
      params.require(:jornada).permit(:cantidad_carreras, :hipodromo_id, :fecha)
    end


    end

app/views/jornadas/_form.html.erb
<div class="form-group">
  <label for="hipodromo_tipo">Hipodromo</label>
  <select size=1 class="form-control" placeholder="Tipo"  name="jornada[hipodromo_id]" id="jornada_hipodromo_id" style = 'width: 40%'/>
  <%for hipodromo in @hipodromos%>
  <option value="<%= hipodromo.id %>"><%= hipodromo.nombre %></option>
  <%end%>

</select>
</div>



<div class="form-group">
  <%= f.label 'Fecha de jornada' %>
  <%fecha_fin = Time.now + 5.days%>
  <%= f.date_field :fecha, min: Time.now, max: fecha_fin,class: "form-control", style: 'width: 20%',  value: Time.now.strftime('%Y-%m-%d')%>
  <span class="help-block"><i>* Este campo es requerido</i><span>
</div>


<div class="form-group">
  <%= f.label 'Cantidad de carreras' %>
  <%= f.text_field :cantidad_carreras, class: "form-control", placeholder: "Cantidad", required: true, id: 'cantidad_carreras', style: 'width: 20%'%>
  <span class="help-block"><i>* Este campo es requerido</i><span>
</div>

<%  if flash[:notice] %>
    <script>
    swal({title: "Lo siento", text: "Ya existe una jornada para la fecha ingresada !",icon: "error", button: "Aceptar"});
    </script>
<% end %>

<div id="caballos">
</div>

app/views/jornadas/edit.html.erb
<%= form_for @jornada, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Editar Jornada</h3>
        </div>

        <div class="box-body">
          <div class="form-group">
            <label for="hipodromo_tipo">Hipodromo</label>
            <select size=1 class="form-control" placeholder="Tipo"  name="carrera[hipodromo_id]" id="carrera_hipodromo_id" />
            <%for hipodromo in @hipodromos%>
            <option value="<%= hipodromo.id %>" <%= hipodromo.id == @hip_act ? "selected":""%>><%= hipodromo.nombre %></option>
            <%end%>

          </select>
          </div>


          <div class="form-group">
            <%= f.label 'Fecha de jornada' %>
            <%= f.date_field :fecha, min: Time.now, max: Time.now.end_of_year,class: "form-control", style: 'width: 20%' %>
            <span class="help-block"><i>* Este campo es requerido</i><span>
          </div>


          <div class="form-group">
            <%= f.label 'Cantidad de carreras' %>
            <%= f.text_field :cantidad_carreras, class: "form-control", placeholder: "Cantidad", required: true %>
            <span class="help-block"><i>* Este campo es requerido</i><span>
          </div>


        </div>

        <div class="box-footer">
          <%= link_to 'Cancelar', jornadas_path, class: 'btn btn-danger' %>
          <%= f.submit 'Enviar', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/jornadas/index.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Listado de Jornadas</h3>
        </div>

        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
                <table id="user_index" class="table table-bordered table-striped dataTable" role="grid">
                  <thead>
                    <tr>
                      <th>Fecha</th>
                      <th>Hipodromo</th>
                      <th>Cantidad de careras</th>
                      <th class="col-xs-1">Acci&oacute;n</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @jornadas.each do |jornada| %>
                      <tr>
                        <td> <%= jornada.fecha.strftime("%d/%m/%Y") %> </td>
                        <td> <%= jornada.hipodromo.nombre %> </td>
                        <td> <%= jornada.cantidad_carreras %> </td>
                        <td>
                          <div class="btn-row">
                            <%= link_to raw('<i class="fa fa-cogs"></i>'), edit_jornada_url(jornada), class: 'btn btn-sm btn-warning' %>
                            <a class="btn btn-sm btn-danger" onclick="borrar_jornada(<%= jornada.id%>)"><i class="fa fa-trash"></i></a>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to 'Nueva Jornada', new_jornada_path, class: 'btn btn-success pull-right' %>
  </div>
</div>



<script>


  function borrar_jornada(id){
        swal({
         title: "ESTA SEGURO DE ELIMINAR ESTA JORNADA?",
         text: "Desea continuar?",
         icon: "warning",
          dangerMode: true,
         buttons: {
         confirm: "Cancelar",
          cancel: "Aceptar",
          },
        })
        .then((willDelete) => {
         if (willDelete) {
         } else {
             axios({
                 method: 'POST',
                   url: '/jornadas/eliminar_jornada',
                 data: {
                     id: id
                 },
               })
               .then(function(response) {
                 swal({title: "Jornada Eliminada", text: "Proceso completo", icon: "success",timer: 2000  }).then((aceptar) => {
                 window.location.href = '/jornadas';
               });

               }

             )
             .catch(function (error) {
               swal("Lo siento", "Ocurrio un error.", "error");
             });
         }
        });
    }
</script>

app/views/jornadas/new.html.erb
<%= form_for @jornada, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Nueva Jornada</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'jornadas/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancelar', jornadas_path, class: 'btn btn-danger' %>
          <%= f.submit 'Enviar', class: "btn btn-success"%>
        </div>

      </div>
    </div>
  </div>
<% end %>